# ============================================================================
# Composite Action — Setup & Cache
# ============================================================================
# A convenience composite action that detects your project language and sets
# up the appropriate runtime with caching. Useful for simple projects.
#
# Usage:
#   - uses: ./.github/actions/setup-and-cache
#     with:
#       language: "python"
#       version: "3.12"
# ============================================================================

name: "Setup & Cache"
description: "Detect and set up language runtime with caching"

inputs:
  language:
    description: "Language: python | node | java | go | rust | dotnet"
    required: true
  version:
    description: "Language/runtime version"
    required: false
    default: ""
  package-manager:
    description: "Package manager (language-specific)"
    required: false
    default: ""
  working-directory:
    description: "Working directory"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    # ── Python ──────────────────────────────────────────────────────────
    - name: Set up Python
      if: inputs.language == 'python'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.version || '3.12' }}
        cache: ${{ inputs.package-manager || 'pip' }}

    # ── Node.js ─────────────────────────────────────────────────────────
    - name: Set up pnpm
      if: inputs.language == 'node' && (inputs.package-manager == 'pnpm')
      uses: pnpm/action-setup@v4
      with:
        version: "9"

    - name: Set up Node.js
      if: inputs.language == 'node'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.version || '20' }}
        cache: ${{ inputs.package-manager || 'npm' }}

    # ── Java ────────────────────────────────────────────────────────────
    - name: Set up Java
      if: inputs.language == 'java'
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.version || '21' }}
        distribution: "temurin"
        cache: ${{ inputs.package-manager || 'maven' }}

    # ── Go ──────────────────────────────────────────────────────────────
    - name: Set up Go
      if: inputs.language == 'go'
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.version || '1.23' }}
        cache-dependency-path: ${{ inputs.working-directory }}/go.sum

    # ── Rust ────────────────────────────────────────────────────────────
    - name: Set up Rust
      if: inputs.language == 'rust'
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.version || 'stable' }}
        components: rustfmt, clippy

    - name: Cache Cargo
      if: inputs.language == 'rust'
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

    # ── .NET ────────────────────────────────────────────────────────────
    - name: Set up .NET
      if: inputs.language == 'dotnet'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.version || '8.0.x' }}
